apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 81
    - name: https
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: guestbook-ui

